site_name: Dpaste Documentation
site_author: DarrenOfficial
site_url: https://docs.dpaste.org
site_description: >-
  dpaste is a pastebin application written in Python using the Django framework.
  You can find a live installation on dpaste.org.
repo_url: 'https://github.com/DarrenOfficial/dpaste'
edit_uri: 'https://github.com/DarrenOfficial/dpaste-docs/edit/main/docs'
theme:
  palette: 
    - scheme: slate 
      primary: 'black'
      accent: 'green'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: 'teal'
      accent: 'green'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  include_search_page: false
  search_index_only: true
  name: material
  font:
    text: "Red Hat Text"
    code: "Roboto Mono"
  favicon:
    'https://darrennathanael.com/favicon.png'
  features:
    - tabs
    - instantsite
    - navigation.tracking
    - navigation.expand
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.suggest
    - toc.integrate
markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
nav:
  - Home: index.md
  - Installations: installation.md
  - Testing: testing.md
  - Management Commands: management_commands.md
  - Settings: settings.md
  - API: api.md
  - ChangeLog: changelog.md
extra:
  social:
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/darrenuselinux'
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/darrenofficial' 
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.darrennathanael.com'
    - icon: 'fontawesome/brands/docker'
      link: 'https://hub.docker.com/r/darrenofficial/dpaste'
  generator: true
copyright: >-
  &copy; 2009 BartTC
  &copy; 2022 Darren Nathanael