site_name: Dpaste Documentation
site_author: DarrenOfficial
site_url: https://docs.dpaste.org
site_description: >-
  dpaste is a pastebin application written in Python using the Django framework.
  You can find a live installation on dpaste.org.
repo_url: 'https://git.dpaste.org/dpaste/dpaste-docs/'
repo_name: 'dpaste'
edit_uri: 'https://git.dpaste.org/dpaste/dpaste-docs/edit/main/docs'

theme:
  palette: 
    - scheme: slate 
      primary: 'black'

  include_search_page: false
  search_index_only: true
  name: material
  font:
    text: Nunito Sans
  favicon:
    'https://lore.dpaste.org/g-brand/v1/favicon-16x16.png'
  features:
    - tabs
    - instantsite
    - navigation.tracking
    - navigation.expand
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.suggest
    - toc.integrate
markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
nav:
  - Home: index.md
  - Installations: installation.md
  - Testing: testing.md
  - Management Commands: management_commands.md
  - Settings: settings.md
  - API: api.md
  - ChangeLog: changelog.md
extra:
  social:
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/darrenuselinux'
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/darrenofficial' 
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.darrennathanael.com'
    - icon: 'fontawesome/brands/docker'
      link: 'https://hub.docker.com/r/darrenofficial/dpaste'
  generator: true
copyright: >-
  &copy; 2013 BartTC
  &copy; 2022 Darren Nathanael
